// backend/frontend-examples/Vue-Example.vue
<template>
  <div :dir="lang === 'ar' ? 'rtl' : 'ltr'">
    <!-- Sélecteur de langue -->
    <div style="text-align: right; margin-bottom: 20px;">
      <button 
        @click="lang = 'fr'"
        :style="{ 
          fontWeight: lang === 'fr' ? 'bold' : 'normal',
          backgroundColor: lang === 'fr' ? '#007bff' : '#f0f0f0'
        }"
      >
        Français
      </button>
      <button 
        @click="lang = 'ar'"
        :style="{ 
          fontWeight: lang === 'ar' ? 'bold' : 'normal',
          backgroundColor: lang === 'ar' ? '#007bff' : '#f0f0f0'
        }"
      >
        العربية
      </button>
    </div>

    <!-- Liste des bâtiments -->
    <div v-if="loading">Chargement...</div>
    <div v-else>
      <h1>{{ lang === 'fr' ? 'Liste des Bâtiments' : 'قائمة المباني' }}</h1>
      
      <div 
        v-for="batiment in batiments" 
        :key="batiment.numbat"
        style="margin-bottom: 20px; padding: 15px; border: 1px solid #ccc;"
      >
        <h2>{{ t(batiment, 'libelleCentre') }}</h2>
        <p>
          <strong>{{ lang === 'fr' ? 'Adresse:' : 'العنوان:' }}</strong>
          {{ t(batiment, 'adresse') }}
        </p>
        <p>
          <strong>{{ lang === 'fr' ? 'Bâtiment:' : 'المبنى:' }}</strong>
          {{ t(batiment, 'libellebat') }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';
import { getTranslatedField } from './translation-helper';

const lang = ref('fr');
const batiments = ref([]);
const loading = ref(true);

// Fonction de traduction
const t = (item, field) => getTranslatedField(item, field, lang.value);

onMounted(async () => {
  // Récupérer la langue depuis localStorage
  const savedLang = localStorage.getItem('lang') || 'fr';
  lang.value = savedLang;
  
  try {
    const res = await axios.get('/api/batiments', {
      params: { codeuser: 'USER001' }
    });
    batiments.value = res.data.batiments;
    loading.value = false;
  } catch (error) {
    console.error('Erreur:', error);
    loading.value = false;
  }
});

// Sauvegarder la langue quand elle change
watch(lang, (newLang) => {
  localStorage.setItem('lang', newLang);
});
</script>

// backend/frontend-examples/React-Example.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { getTranslatedField } from './translation-helper';

/**
 * Exemple d'utilisation dans React
 */
const BatimentList = () => {
  const [lang, setLang] = useState('fr'); // 'fr' ou 'ar'
  const [batiments, setBatiments] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Récupérer la langue depuis localStorage
    const savedLang = localStorage.getItem('lang') || 'fr';
    setLang(savedLang);
    
    // Charger les bâtiments
    axios.get('/api/batiments', {
      params: { codeuser: 'USER001' }
    })
    .then(res => {
      setBatiments(res.data.batiments);
      setLoading(false);
    })
    .catch(err => {
      console.error('Erreur:', err);
      setLoading(false);
    });
  }, []);

  const handleLangChange = (newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  };

  if (loading) return <div>Chargement...</div>;

  return (
    <div style={{ direction: lang === 'ar' ? 'rtl' : 'ltr' }}>
      {/* Sélecteur de langue */}
      <div style={{ textAlign: 'right', marginBottom: '20px', padding: '10px' }}>
        <button 
          onClick={() => handleLangChange('fr')}
          style={{ 
            marginRight: '10px',
            fontWeight: lang === 'fr' ? 'bold' : 'normal',
            backgroundColor: lang === 'fr' ? '#007bff' : '#f0f0f0',
            color: lang === 'fr' ? 'white' : 'black'
          }}
        >
          Français
        </button>
        <button 
          onClick={() => handleLangChange('ar')}
          style={{ 
            fontWeight: lang === 'ar' ? 'bold' : 'normal',
            backgroundColor: lang === 'ar' ? '#007bff' : '#f0f0f0',
            color: lang === 'ar' ? 'white' : 'black'
          }}
        >
          العربية
        </button>
      </div>

      {/* Liste des bâtiments */}
      <div>
        <h1>{lang === 'fr' ? 'Liste des Bâtiments' : 'قائمة المباني'}</h1>
        
        {batiments.map(batiment => (
          <div 
            key={batiment.numbat}
            style={{ 
              marginBottom: '20px', 
              padding: '15px', 
              border: '1px solid #ccc',
              borderRadius: '5px'
            }}
          >
            <h2>{getTranslatedField(batiment, 'libelleCentre', lang)}</h2>
            <p>
              <strong>{lang === 'fr' ? 'Adresse:' : 'العنوان:'}</strong>{' '}
              {getTranslatedField(batiment, 'adresse', lang)}
            </p>
            <p>
              <strong>{lang === 'fr' ? 'Bâtiment:' : 'المبنى:'}</strong>{' '}
              {getTranslatedField(batiment, 'libellebat', lang)}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
};

/**
 * Exemple avec les détails d'un bon d'entrée
 */
const StockEntryDetail = ({ nummvt }) => {
  const [lang, setLang] = useState('fr');
  const [details, setDetails] = useState(null);

  useEffect(() => {
    axios.get(`/api/detail-stock-entry/${nummvt}`)
      .then(res => setDetails(res.data.data))
      .catch(err => console.error(err));
  }, [nummvt]);

  if (!details) return <div>Chargement...</div>;

  return (
    <div style={{ direction: lang === 'ar' ? 'rtl' : 'ltr' }}>
      <select value={lang} onChange={(e) => setLang(e.target.value)}>
        <option value="fr">Français</option>
        <option value="ar">العربية</option>
      </select>

      <table>
        <thead>
          <tr>
            <th>{lang === 'fr' ? 'Article' : 'المادة'}</th>
            <th>{lang === 'fr' ? 'Quantité' : 'الكمية'}</th>
            <th>{lang === 'fr' ? 'Unité' : 'الوحدة'}</th>
          </tr>
        </thead>
        <tbody>
          {details.map((line, index) => (
            <tr key={index}>
              <td>{getTranslatedField(line, 'desart', lang)}</td>
              <td>{line.qteart}</td>
              <td>{getTranslatedField(line, 'unite', lang)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

/**
 * Exemple avec les fournisseurs
 */
const FournisseurSelect = ({ value, onChange }) => {
  const [lang, setLang] = useState('fr');
  const [fournisseurs, setFournisseurs] = useState([]);

  useEffect(() => {
    axios.get('/api/fournisseurs')
      .then(res => setFournisseurs(res.data.fournisseurs))
      .catch(err => console.error(err));
  }, []);

  return (
    <select value={value} onChange={onChange}>
      <option value="">{lang === 'fr' ? 'Sélectionner...' : 'اختر...'}</option>
      {fournisseurs.map(frs => (
        <option key={frs.code} value={frs.code}>
          {getTranslatedField(frs, 'libelle', lang)}
        </option>
      ))}
    </select>
  );
};

export { BatimentList, StockEntryDetail, FournisseurSelect };
